// Inlines /corpus dialect data into src/generated/corpus.ts so the library has no runtime file access.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const corpus = join(here, '..', '..', '..', 'corpus');
const read = (p) => JSON.parse(readFileSync(join(corpus, p), 'utf8'));

const order = read('dialects/index.json');
const dialects = Object.fromEntries(order.map((id) => [id, read(`dialects/${id}.json`)]));
const strategies = read('strategies.json');

const out =
  '// GENERATED by scripts/gen-corpus.mjs from /corpus. Do not edit.\n' +
  `export const DIALECT_ORDER: string[] = ${JSON.stringify(order)};\n` +
  `export const DIALECT_DATA: unknown = ${JSON.stringify(dialects)};\n` +
  `export const STRATEGY_IDS: unknown = ${JSON.stringify(strategies)};\n`;

const target = join(here, '..', 'src', 'generated');
mkdirSync(target, { recursive: true });
writeFileSync(join(target, 'corpus.ts'), out);
console.log(`generated src/generated/corpus.ts (${order.length} dialects)`);
